### ISSUE TITLE
Fazer o menu lateral (Sider)

### ISSUE THREAD

**Issue by LuSizilio** [q-box/src-ui#18]

**Comment by leonardo-minora** [comment]
Criado com o commit f0c3affb56fad66c4e5457e8496a4a95334a6043

Precisa : 
- [x] programar o botão para fazer esconder e aparecer o sider.
- [x] programar o tamanho do sider para o tamanho da tela no mobile

**Comment by LuSizilio** [comment]
Foi feito com Drawer no lugar de Sider
