### ISSUE TITLE
Protótipo em SketchUp

### ISSUE THREAD

**Issue by victordaniel102** [q-box/src-ui#9]

**Comment by leonardo-minora** [comment]
[versão inicial](https://github.com/q-box/ui-prototypes/blob/master/logo/logo-v1.png)

**Comment by leonardo-minora** [comment]
confundi as issues :P

**Comment by victordaniel102** [comment]
[parte do protótipo v3](https://github.com/q-box/ui-prototypes/blob/master/prototypes-ui-v3/prototype-ui-v3.png)
